### ISSUE TITLE
cli tutorial

### ISSUE THREAD

**Issue by campones** [applesh00ter/telerising-api#3]
Hi

I would like to know if there could be a little tutorial about the cli usage of this api. I m using it via ssh on ubuntu server
Right now I just copied the settings.json of the windows home computer on the server and it works as well, but maybe it could be nicer to control it directly from the server
thanks

**Comment by applesh00ter** [comment]
There is no CLI interface for the Telerising API.
Everything is managed with the builtin Webinterface.

If you are not familiar with Linux, I don't recommend setting up the API on a publicly available server.

**Comment by campones** [comment]
thanks, obviously I didn't even think about it... it can be accessed remotely like webmin or whatever service running on a dedicated port...  that's great :)  
and yes, I  m pretty familiar with linux ! ..
