### ISSUE TITLE
Nello Bitrate selection

### ISSUE THREAD

**Issue by campones** [applesh00ter/telerising-api#4]
Hi
I realize it's probably better to ask here in github than in the forum (for the language issue.. )  less disturbing for everyone I guess.

So here is the thing: when I used to manually grab the master m3u8 from nello site I got something like this : 

`ffmpeg -i "https://nello-ott.customers.xcdn.iptv.ch/v1/hls/ott/tv/1/2062/index.m3u8?content_location=x-poseidon&adap=mobile&token=xxx&expires=xxx"
ffmpeg version 4.4.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: 
(...verbose output)

Input #0, hls, from 'https://nello-ott.customers.xcdn.iptv.ch/v1/hls/ott/tv/1/2062/index.m3u8?content_location=x-poseidon&adap=mobile&token=xxx&expires=xxx':
  Duration: N/A, start: 57406.917156, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 4002000
  Stream #0:1(fr): Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      variant_bitrate : 4445400
      comment         : French
  Stream #0:2(und): Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 127 kb/s
    Metadata:
      variant_bitrate : 4445400
      comment         : Unknown
  Stream #0:3: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 4002000
  Program 1
    Metadata:
      variant_bitrate : 482000
  Stream #0:0(fr): Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 64 kb/s (default)
    Metadata:
      comment         : French
  Stream #0:4: Video: h264 (Constrained Baseline) ([27][0][0][0] / 0x001B), yuv420p, 320x180 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 482000
  Program 2
    Metadata:
      variant_bitrate : 635200
  Stream #0:0(fr): Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 64 kb/s (default)
    Metadata:
      comment         : French
  Stream #0:5: Video: h264 (Constrained Baseline) ([27][0][0][0] / 0x001B), yuv420p, 400x224 [SAR 1:1 DAR 25:14], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 635200
  Program 3
    Metadata:
      variant_bitrate : 1500400
  Stream #0:1(fr): Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      variant_bitrate : 4445400
      comment         : French
  Stream #0:2(und): Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 127 kb/s
    Metadata:
      variant_bitrate : 4445400
      comment         : Unknown
  Stream #0:6: Video: h264 (Constrained Baseline) ([27][0][0][0] / 0x001B), yuv420p, 720x404 [SAR 1:1 DAR 180:101], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 1500400
  Program 4
    Metadata:
      variant_bitrate : 2328400
  Stream #0:1(fr): Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      variant_bitrate : 4445400
      comment         : French
  Stream #0:2(und): Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 127 kb/s
    Metadata:
      variant_bitrate : 4445400
      comment         : Unknown
  Stream #0:7: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 720x404 [SAR 1:1 DAR 180:101], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 2328400
  Program 5
    Metadata:
      variant_bitrate : 3372000
  Stream #0:1(fr): Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      variant_bitrate : 4445400
      comment         : French
  Stream #0:2(und): Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 127 kb/s
    Metadata:
      variant_bitrate : 4445400
      comment         : Unknown
  Stream #0:8: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 3372000
  Program 6
    Metadata:
      variant_bitrate : 4445400
  Stream #0:1(fr): Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      variant_bitrate : 4445400
      comment         : French
  Stream #0:2(und): Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 127 kb/s
    Metadata:
      variant_bitrate : 4445400
      comment         : Unknown
  Stream #0:9: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 4445400
At least one output file must be specified`

So as you can see, there are like 7 qualities/bitrates available (1080p,180p,224p,404p [1500400 / 2328400 bitrates] 720p [3372000 / 4445400 ]) but in the telerising backend, I can only chose among 3

![66051117ac1b4d870e9ac817630510fb](https://user-images.githubusercontent.com/7072524/224479829-50cb6484-1b2e-496b-a8fc-6a896c447bfc.png)

Is there a workaround here?

**Comment by applesh00ter** [comment]
There is no general need for lower bitrates. Because of that only the most used bitrates are implemented in Telerising.
If you want to have the full Nello experience, you should use their Webversion to watch the streams.

**Comment by campones** [comment]
actually that's not a good answer because the interface also provide the 404p which is very low these days while avoiding a smaller 720p quality.   Depending of your usage and home internet, it can makes a big difference to have a lower bitrate. 

I have managed to add options by adding some options in the providers.json  still have to find out which number is egal to an existing resolution or not.  

`    "available_qualities": ["8000", "5000", "4999", "3000", "2999", "1500"],`

![666fb3a94a0fee04aba1d746038e5312](https://user-images.githubusercontent.com/7072524/224480599-85d94450-613c-4755-b432-4cb71d1163a2.png)

**Comment by campones** [comment]
So far I got :

`    "available_qualities": ["8000", "5000", "4999", "1500"],`


8000  = 1080p
4999  = 1080p (actually seems a duplicate/mistake since there is only one 1080p in the playlist I showed earlier)
5000  = 720p/50
1500  = 404p/25

So I believe there is a confusion between the 1080p and the 720p. The api falsely retrieves the same 1080p instead of the alternative 720p quality that is available?  Not sure, only easy4me could tell I guess
